[package]
name = "leptos-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
bytes = "1.9.0"
leptos = { version = "0.7.0", features = ["csr"] }
leptos-use = "0.14.0"
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.133"
